### ISSUE TITLE
BP-4009 buckarooFee.title is not a function

### ISSUE THREAD

**Issue by onepack** [buckaroo-it/Magento2#1108]
Since we updated Magento to 2.4.7-p3 we get this issue at the checkout for every payment method.

Your PHP version: 8.1.30
Buckaroo version: 1.50.2 

Uncaught TypeError: window.checkoutConfig.buckarooFee.title is not a function

Uncaught TypeError: window.checkoutConfig.buckarooFee.title is not a function
    selectPaymentMethod https://domain.com/static/version1731686103/frontend/Themebase/theme/nl_NL/Buckaroo_Magento2/js/view/payment/method-renderer/ideal.js:151
    init https://domain.com/static/version1731686103/frontend/Themebase/theme/nl_NL/knockoutjs/knockout.js:4669
    jQuery 5

**Comment by Buckaroo-Rene** [comment]
Hi @onepack ,

Thank you for reporting this issue. We have developed a fix, which will be included in our next release.
The fix is currently undergoing testing, and we will keep you updated when a new release is available containing this fix.

**Comment by richardreen** [comment]
We are several weeks later and still there is no solutioh for this error!!! 
I wrote several email, no solution. We are facing this error now for weeks....losing sales now!!

**Comment by SandervdHulst** [comment]
Hi @richardreen,
Thank you for your message. We are currently in the final phase of testing for our next release, which is planned for the first half of January. This problem is part of the upcoming release.

Additionally, we have prepared a Pull Request to address this issue: https://github.com/buckaroo-it/Magento2/pull/1119
You could consider to checkout this specific Pull Request.

**Comment by Buckaroo-Rene** [comment]
Hi @onepack & @richardreen ,

A fix has been implemented and is now available in [v1.51.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.51.0).

**Comment by MatthijsvanNoort** [comment]
This doesn't work with FireCheckout for certain stores.
Still getting this error. 

There is no error checking of fallback in the various payment method js's

for example, if you pick ideal.js and comment out 
`// window.checkoutConfig.buckarooFee.title(this.paymentFeeLabel);
`
everything then the payment method works

I see in totals.js (the change that is in the latest version) 
            window.checkoutConfig.buckarooFee.title = ko.observable(options.title);

but there's no error checking here. Apparently ko.observable(options.title) fails, then everything fails.

**Comment by LeanderMatse** [comment]
Same issue. Unable to select any payment. 

Magento 2.4.7-p3
buckaroo/magento2 1.51.0

**Comment by Buckaroo-Rene** [comment]
Hi @MatthijsvanNoort , @coughsyrupgit & @LeanderMatse,

We’ve identified the cause of the issue and implemented a solution https://github.com/buckaroo-it/Magento2/pull/1158.
This fix will be released in a hotfix once testing is fully completed.

So far, one merchant has confirmed that it works when testing with our '[develop](https://github.com/buckaroo-it/Magento2/tree/develop)' branch that contains the fix for the payment fee title and also some CSP improvements.
Could you also help verify that the payment fee title is working correctly in this branch?

Please use the '[develop branch](https://github.com/buckaroo-it/Magento2/tree/develop)' only for confirmation to ensure everything functions as expected.

Best regards,
René

**Comment by richardreen** [comment]
Is there any planning when this fix will be available for all, because my customers complaining that the checkout is sometimes not working!!
I did install it on my staging server and it works there without problems and the original problem looks to be solved!!

gr.

Richard

**Comment by Buckaroo-Rene** [comment]
Hi @richardreen , @MatthijsvanNoort , @coughsyrupgit & @LeanderMatse ,

Hereby I would like to inform you that the fix is now available in [version 1.51.1](https://github.com/buckaroo-it/Magento2/releases/tag/v1.51.1) of the plugin.

Best Regards,
René

**Comment by richardreen** [comment]
Hi There,

Try to install that new version by composer, but no new version installed!!!!



Gr..

Richard

**Comment by ShuCh3n** [comment]
@richardreen  Can you remove composer.lock and also check if the correct version is specified in your composer.json?

**Comment by Buckaroo-Rene** [comment]
Hi @richardreen & @coughsyrupgit ,

Thanks for confirming, both of you.
Glad to hear the issue is resolved!
